server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/placement_db
spring.datasource.username=root
spring.datasource.password=vikootreddy@2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false
spring.sql.init.mode=never

app.jwt.secret=ChangeThisSecretToARealKey1234567890
app.jwt.expiration-ms=86400000

seed.refresh.enabled=true
seed.refresh.fixed-rate-ms=3600000
seed.data.students=500
seed.data.companies=80
